# Generated by Django 5.0.6 on 2025-08-21 23:41

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(db_column="factura_id", primary_key=True, serialize=False),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("ot_id", models.BigIntegerField(db_column="ot_id", null=True)),
                (
                    "emitida_por_user_id",
                    models.BigIntegerField(db_column="emitida_por_user_id", null=True),
                ),
                ("estado", models.CharField(max_length=10)),
                ("fecha_emision", models.DateTimeField()),
                ("moneda", models.CharField(max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("impuestos", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("descuento", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="customers.cliente",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        db_column="vehiculo_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.vehiculo",
                    ),
                ),
            ],
            options={
                "db_table": "factura",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="factura_item_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("repuesto", "Repuesto"), ("mano_obra", "Mano de obra")],
                        max_length=12,
                    ),
                ),
                ("repuesto_id", models.BigIntegerField(blank=True, null=True)),
                ("descripcion", models.TextField()),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("impuestos", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "total",
                    models.GeneratedField(
                        db_column="total",
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("cantidad"), "*", models.F("precio_unitario")
                            ),
                            "+",
                            models.F("impuestos"),
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=14),
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        db_column="factura_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "factura_item",
                "ordering": ["id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="presupuesto_id", primary_key=True, serialize=False
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                (
                    "creado_por_user_id",
                    models.BigIntegerField(db_column="creado_por_user_id", null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("anulado", "Anulado"),
                        ],
                        default="borrador",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_emision", models.DateTimeField()),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("impuestos", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("descuento", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="customers.cliente",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        db_column="vehiculo_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.vehiculo",
                    ),
                ),
            ],
            options={
                "db_table": "presupuesto",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="presupuesto",
            field=models.ForeignKey(
                db_column="presupuesto_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.quote",
            ),
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="presupuesto_item_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("repuesto", "Repuesto"), ("mano_obra", "Mano de obra")],
                        max_length=12,
                    ),
                ),
                ("repuesto_id", models.BigIntegerField(blank=True, null=True)),
                ("descripcion", models.TextField()),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("impuestos", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "total",
                    models.GeneratedField(
                        db_column="total",
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("cantidad"), "*", models.F("precio_unitario")
                            ),
                            "+",
                            models.F("impuestos"),
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=14),
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        db_column="presupuesto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.quote",
                    ),
                ),
            ],
            options={
                "db_table": "presupuesto_item",
                "ordering": ["id"],
                "managed": True,
            },
        ),
    ]
