# Generated by Django 5.0.6 on 2025-08-21 23:41

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(db_column="repuesto_id", primary_key=True, serialize=False),
                ),
                ("sku", models.CharField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("costo_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                "verbose_name": "Repuesto",
                "verbose_name_plural": "Repuestos",
                "db_table": "repuesto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventoryMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="movimiento_id", primary_key=True, serialize=False
                    ),
                ),
                ("tipo", models.CharField(max_length=10)),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                ("costo_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "total_costo",
                    models.GeneratedField(
                        db_column="total_costo",
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("cantidad"), "*", models.F("costo_unitario")
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=14),
                    ),
                ),
                ("referencia", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "repuesto",
                    models.ForeignKey(
                        db_column="repuesto_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="inventory.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "db_table": "movimiento_inventario",
                "managed": True,
            },
        ),
    ]
