# Generated by Django 5.0.6 on 2025-08-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(db_column="cliente_id", primary_key=True, serialize=False),
                ),
                ("razon_social", models.CharField(max_length=150)),
                ("documento", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("codigo_postal", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "cliente",
                "ordering": ["razon_social", "id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(db_column="vehiculo_id", primary_key=True, serialize=False),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("vin", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("marca", models.CharField(blank=True, max_length=50, null=True)),
                ("modelo", models.CharField(blank=True, max_length=50, null=True)),
                ("anio", models.SmallIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vehiculos",
                        to="customers.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "vehiculo",
                "managed": True,
                "indexes": [models.Index(fields=["cliente"], name="idx_vehiculo_cliente_dj")],
            },
        ),
    ]
