# Generated by Django 5.0.6 on 2025-08-21 23:41

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                ("id", models.BigAutoField(db_column="ot_id", primary_key=True, serialize=False)),
                ("numero", models.CharField(max_length=30, unique=True)),
                (
                    "asignado_a_user_id",
                    models.BigIntegerField(
                        blank=True, db_column="asignado_a_user_id", default=None, null=True
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(blank=True, db_column="fecha_ingreso", null=True),
                ),
                (
                    "fecha_salida",
                    models.DateTimeField(blank=True, db_column="fecha_salida", null=True),
                ),
                (
                    "matricula",
                    models.CharField(blank=True, db_column="matricula", max_length=20, null=True),
                ),
                (
                    "color",
                    models.CharField(blank=True, db_column="color", max_length=30, null=True),
                ),
                (
                    "kilometraje",
                    models.IntegerField(blank=True, db_column="kilometraje", null=True),
                ),
                (
                    "ingresado_en_grua",
                    models.BooleanField(db_column="ingresado_en_grua", default=False),
                ),
                (
                    "datos_adicionales",
                    models.TextField(blank=True, db_column="datos_adicionales", null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_progreso", "En progreso"),
                            ("finalizada", "Finalizada"),
                            ("anulada", "Anulada"),
                        ],
                        default="abierta",
                        max_length=12,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("impuestos", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("descuento", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ordenes",
                        to="customers.cliente",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        db_column="vehiculo_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ordenes",
                        to="customers.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Trabajo",
                "verbose_name_plural": "Órdenes de Trabajo",
                "db_table": "orden_trabajo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(db_column="ot_item_id", primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("repuesto", "Repuesto"), ("mano_obra", "Mano de obra")],
                        max_length=12,
                    ),
                ),
                ("repuesto_id", models.BigIntegerField(blank=True, null=True)),
                ("descripcion", models.TextField()),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("impuestos", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "total",
                    models.GeneratedField(
                        db_column="total",
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("cantidad"), "*", models.F("precio_unitario")
                            ),
                            "+",
                            models.F("impuestos"),
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=14),
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        db_column="ot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de OT",
                "verbose_name_plural": "Ítems de OT",
                "db_table": "ot_item",
                "managed": True,
            },
        ),
    ]
